node_url: https://fullnode.testnet.aptoslabs.com/v1
node_urls:
  - https://fullnode.testnet.aptoslabs.com/v1
  - https://aptos-testnet.blockeden.xyz/fgxchgx48sALxGNo3UsC/v1

redis_url: redis://test-env.dpjsjb.clustercfg.memorydb.us-east-1.amazonaws.com:6379
fixed_market:
  event_handle: 0x0d42d82754ff68a86b11e10ffb91e8bda89a8b14f587dce7244b97279d19a965::fixed_price_market::FixedMarketEvents
  event_fields:
    - buy_token_events
    - list_token_events
    - delist_token_events
offer:
  event_handle: 0x0d42d82754ff68a86b11e10ffb91e8bda89a8b14f587dce7244b97279d19a965::offer::OfferEvents
  event_fields:
    - offer_token_events
    - accept_offer_events
    - cancel_offer_events
creation:
  event_handle: 0x0d42d82754ff68a86b11e10ffb91e8bda89a8b14f587dce7244b97279d19a965::creation::CreationEvents
  event_fields:
    - collection_created_events
    - token_created_events
curation:
  event_handle: 0x5e895990e6134dc0e5774090b5657410e78713a1ae4839870857a1b57bd370b4::curation::CurationEvents
  event_fields:
    - gallery_created_events
    - offer_created_events
    - offer_accepted_events
    - offer_rejected_events
    - offer_canceled_events
    - exhibit_listed_events
    - exhibit_canceled_events
    - exhibit_sold_events
    - exhibit_frozen_events
    - exhibit_redeemed_events
