node_url: https://fullnode.testnet.aptoslabs.com/v1
node_urls:
  - https://fullnode.testnet.aptoslabs.com/v1
  - https://aptos-testnet.blockeden.xyz/fgxchgx48sALxGNo3UsC/v1

redis_url: redis://test-env.dpjsjb.clustercfg.memorydb.us-east-1.amazonaws.com:6379
fixed_market:
  event_handle: 0x73545daede11168cbe4f5503f19929c7eebb888cffef27983ed374515f7e82a1::fixed_price_market::FixedMarketEvents
  event_fields:
    - buy_token_events
    - list_token_events
    - delist_token_events
offer:
  event_handle: 0x73545daede11168cbe4f5503f19929c7eebb888cffef27983ed374515f7e82a1::offer::OfferEvents
  event_fields:
    - offer_token_events
    - accept_offer_events
    - cancel_offer_events
creation:
  event_handle: 0x73545daede11168cbe4f5503f19929c7eebb888cffef27983ed374515f7e82a1::creation::CreationEvents
  event_fields:
    - collection_created_events
    - token_created_events
curation:
  event_handle: 0x73545daede11168cbe4f5503f19929c7eebb888cffef27983ed374515f7e82a1::curation::CurationEvents
  event_fields:
    - offer_events
    - gallery_events
    - exhibit_events
