version: '3.9'
services:
  event-worker-aptos:
    working_dir: /app/event-worker-aptos
    restart: always
    image: event-worker-aptos:v1
    volumes:
      - ./aptos:/app/event-worker-aptos
    command: /bin/sh -c "prisma generate  && python3 ./main.py"
  event-worker-eth:
    working_dir: /app/event-worker-ethereum
    restart: always
    environment:
      - CONTRACT_CURATION=${ETH_CONTRACT_CURATION}
      - CONTRACT_SINGLE_COLLECTIVE=${ETH_CONTRACT_SINGLE_COLLECTIVE}
      - CONTRACT_MULTIPLE_COLLECTIVE=${ETH_CONTRACT_MULTIPLE_COLLECTIVE}
      - PROVIDERS=${ETH_PROVIDERS}
      - DURATION_MILLIS=${DURATION_MILLIS}
      - EVENTOFFSET_ID=1
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - CHAIN=ETH
    image: event-worker-eth:v1
    volumes:
      - ./evm:/app/event-worker-eth
    command: /bin/sh -c "npx prisma generate && yarn start"
  event-worker-polygon:
    working_dir: /app/event-worker-polygon
    restart: always
    environment:
      - CONTRACT_CURATION=${POLYGON_CONTRACT_CURATION}
      - CONTRACT_SINGLE_COLLECTIVE=${POLYGON_CONTRACT_SINGLE_COLLECTIVE}
      - CONTRACT_MULTIPLE_COLLECTIVE=${POLYGON_CONTRACT_MULTIPLE_COLLECTIVE}
      - PROVIDERS=${POLYGON_PROVIDERS}
      - DURATION_MILLIS=${DURATION_MILLIS}
      - EVENTOFFSET_ID=2
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - CHAIN=POLYGON
    image: event-worker-polygon:v1
    volumes:
     - ./evm:/app/event-worker-polygon
    command: /bin/sh -c "npx prisma generate && yarn start"
  event-worker-bsc:
    working_dir: /app/event-worker-bsc
    restart: always
    environment:
      - CONTRACT_CURATION=${BSC_CONTRACT_CURATION}
      - CONTRACT_SINGLE_COLLECTIVE=${BSC_CONTRACT_SINGLE_COLLECTIVE}
      - CONTRACT_MULTIPLE_COLLECTIVE=${BSC_CONTRACT_MULTIPLE_COLLECTIVE}
      - PROVIDERS=${BSC_PROVIDERS}
      - DURATION_MILLIS=${DURATION_MILLIS}
      - EVENTOFFSET_ID=3
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - CHAIN=BSC
    image: event-worker-bsc:v1
    volumes:
     - ./evm:/app/event-worker-bsc
    command: /bin/sh -c "npx prisma generate && yarn start"
  automint: 
    working_dir: /app/automint
    restart: always
    environment:
      - CONTRACT_CURATION=${ETH_CONTRACT_CURATION}
      - CONTRACT_SINGLE_COLLECTIVE=${ETH_CONTRACT_SINGLE_COLLECTIVE}
      - CONTRACT_MULTIPLE_COLLECTIVE=${ETH_CONTRACT_MULTIPLE_COLLECTIVE}
      - PROVIDERS=${ETH_PROVIDERS}
      - DURATION_MILLIS=${DURATION_MILLIS}
      - EVENTOFFSET_ID=1
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - PRIVATE_KEY_TEST_ONLY=${PRIVATE_KEY_TEST_ONLY}
    image: automint:v1
    volumes:
      - ./evm:/app/automint
    command: /bin/sh -c "npx prisma generate && yarn automint"
