version: '3.9'
services:
  indexer-apt:
    working_dir: /app/indexer-apt
    restart: always
    image: indexer-apt:v1
    volumes:
      - ./apt:/app/indexer-apt
    command: /bin/sh -c "prisma generate  && python3 ./main.py"
  indexer-eth:
    working_dir: /app/indexer-eth
    restart: always
    environment:
      - CONTRACT_LOTTERY=${ETH_CONTRACT_LOTTERY}
      - CONTRACT_CURATION=${ETH_CONTRACT_CURATION}
      - CONTRACT_SINGLE_COLLECTIVE=${ETH_CONTRACT_SINGLE_COLLECTIVE}
      - CONTRACT_MULTIPLE_COLLECTIVE=${ETH_CONTRACT_MULTIPLE_COLLECTIVE}
      - PROVIDERS=${ETH_PROVIDERS}
      - DURATION_MILLIS=${DURATION_MILLIS}
      - EVENTOFFSET_ID=1
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - CHAIN=ETH
      - NETWORK=${NETWORK}
    image: indexer-eth:v1
    volumes:
      - ./evm:/app/indexer-eth
    command: /bin/sh -c "npx prisma generate && yarn start"
  indexer-pol:
    working_dir: /app/indexer-pol
    restart: always
    environment:
      - CONTRACT_CURATION=${POLYGON_CONTRACT_CURATION}
      - CONTRACT_SINGLE_COLLECTIVE=${POLYGON_CONTRACT_SINGLE_COLLECTIVE}
      - CONTRACT_MULTIPLE_COLLECTIVE=${POLYGON_CONTRACT_MULTIPLE_COLLECTIVE}
      - PROVIDERS=${POLYGON_PROVIDERS}
      - DURATION_MILLIS=${DURATION_MILLIS}
      - EVENTOFFSET_ID=2
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - CHAIN=POLYGON
      - NETWORK=${NETWORK}
    image: indexer-pol:v1
    volumes:
     - ./evm:/app/indexer-pol
    command: /bin/sh -c "npx prisma generate && yarn start"
  indexer-bsc:
    working_dir: /app/indexer-bsc
    restart: always
    environment:
      - CONTRACT_CURATION=${BSC_CONTRACT_CURATION}
      - CONTRACT_SINGLE_COLLECTIVE=${BSC_CONTRACT_SINGLE_COLLECTIVE}
      - CONTRACT_MULTIPLE_COLLECTIVE=${BSC_CONTRACT_MULTIPLE_COLLECTIVE}
      - PROVIDERS=${BSC_PROVIDERS}
      - DURATION_MILLIS=${DURATION_MILLIS}
      - EVENTOFFSET_ID=3
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - CHAIN=BSC
      - NETWORK=${NETWORK}
    image: indexer-bsc:v1
    volumes:
     - ./evm:/app/indexer-bsc
    command: /bin/sh -c "npx prisma generate && yarn start"
  indexer-opbnb:
    working_dir: /app/indexer-opbnb
    restart: always
    environment:
      - CONTRACT_CURATION=${OPBNB_CONTRACT_CURATION}
      - CONTRACT_SINGLE_COLLECTIVE=${OPBNB_CONTRACT_SINGLE_COLLECTIVE}
      - CONTRACT_MULTIPLE_COLLECTIVE=${OPBNB_CONTRACT_MULTIPLE_COLLECTIVE}
      - PROVIDERS=${OPBNB_PROVIDERS}
      - DURATION_MILLIS=${DURATION_MILLIS}
      - EVENTOFFSET_ID=4
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - CHAIN=OPBNB
      - NETWORK=${NETWORK}
    image: indexer-opbnb:v1
    volumes:
      - ./evm:/app/indexer-opbnb
    command: /bin/sh -c "npx prisma generate && yarn start"
  indexer-zksync:
    working_dir: /app/indexer-zksync
    restart: always
    environment:
      - CONTRACT_CURATION=${ZKSYNC_CONTRACT_CURATION}
      - CONTRACT_SINGLE_COLLECTIVE=${ZKSYNC_CONTRACT_SINGLE_COLLECTIVE}
      - CONTRACT_MULTIPLE_COLLECTIVE=${ZKSYNC_CONTRACT_MULTIPLE_COLLECTIVE}
      - PROVIDERS=${ZKSYNC_PROVIDERS}
      - DURATION_MILLIS=${DURATION_MILLIS}
      - EVENTOFFSET_ID=5
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - CHAIN=ZKSYNC
      - NETWORK=${NETWORK}
    image: indexer-zksync:v1
    volumes:
      - ./evm:/app/indexer-zksync
    command: /bin/sh -c "npx prisma generate && yarn start"
  automint: 
    working_dir: /app/automint
    restart: always
    environment:
      - CONTRACT_CURATION=${ETH_CONTRACT_CURATION}
      - CONTRACT_SINGLE_COLLECTIVE=${ETH_CONTRACT_SINGLE_COLLECTIVE}
      - CONTRACT_MULTIPLE_COLLECTIVE=${ETH_CONTRACT_MULTIPLE_COLLECTIVE}
      - PROVIDERS=${ETH_PROVIDERS}
      - DURATION_MILLIS=${DURATION_MILLIS}
      - EVENTOFFSET_ID=1
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - PRIVATE_KEY_TEST_ONLY=${PRIVATE_KEY_TEST_ONLY}
    image: automint:v1
    volumes:
      - ./evm:/app/automint
    command: /bin/sh -c "npx prisma generate && yarn automint"
