version: '3.5'

services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 88888888
      PGDATA: /data/postgres
    volumes:
        - postgres-db:/data/postgres
    ports:
      - "5433:5432"
  redis:
    container_name: redis_db
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - redis-db:/data/redis
    ports:
      - "6379:6379"
  api_express:
      working_dir: /api/express_app
      restart: always
      environment:
        - DATABASE_URL= 'postgresql://postgres:88888888@localhost:5433/mixverse?schema=public&connect_timeout=3000'
        - REDIS_URL = redis://localhost:6379
      build: ./ 
      volumes:
        - api-express:/api/express_app
      command: /bin/sh -c "npm run prisma && npm run dev"

      ports:
        - "8000:6060"
volumes:
  postgres-db:
    driver: local # linux : /var/lib/docker/volumes  windows:\\wsl.localhost\docker-desktop-data\data\docker\volumes
  api-express:
    driver: local
  redis-db:
    driver: local

# docker-compose up -d
# docker ps
# docker stop postgres_db